import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Torneos de tenis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg-primary`}>
        <Providers>
          <Navbar />
          <section className="flex items-center justify-center h-auto min-h-screen my-6">
            <div className="w-auto h-auto bg-bg-secondary rounded-md pb-2">
              {children}
            </div>
          </section>
        </Providers>
      </body>
    </html>
  );
}
